min_trimmed_length = 2
min_word_count = 1
max_word_count = 14
min_characters = 3
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = false
needs_letter_start = true
needs_uppercase_start = true
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;", " :", "( ", " )"]
allowed_symbols_regex = "[a-ząćęłńóśżźA-ZĄĆĘŁŃÓŚŻŹ ,.?!:\\-–—\"'„“”\\(\\)]"

abbreviation_patterns = [
  "[A-ZĄĆĘŁŃÓŚŻŹ]{2,}",
  "(?i)[a-ząćęłńóśżź]\\. ?[a-ząćęłńóśżź]",
  # Abbrevations without a period
  "(?i) (bp|dr|nr|mgr|mjr|płk|wg|dra)\\.? "
]

replacements = [
  ["p.n.e.", "przed naszą erą"],
  ["n.e.", "naszej ery"],
  ["n.p.m.", "nad poziomem morza"],
  ["np. ", "na przykład "],
  ["n.p. ", "na przykład "],
  ["tj. ", "to jest "],
  ["m.in. ", "między innymi "],
  ["tzn. ", "to znaczy "],
  ["im. ", "imienia "],
  ["przy ul. ", "przy ulicy "],
  ["ul. ", "ulica "],
  ["ok. ", "około "],
  ["jw. ", "jak wyżej "],
  ["ds. ", "do spraw "],
  # Centuries
  ["w XXXIX wieku", "w trzydziestym dziewiątym wieku"], 
  ["XXXIX wieku", "trzydziestego dziewiątego wieku"], 
  ["XXXIX wiek", "trzydziesty dziewiąty wiek"], 
  ["koniec XXXIX w.", "koniec trzydziestego dziewiątego wieku"], 
  ["końca XXXIX w.", "końca trzydziestego dziewiątego wieku"], 
  ["początek XXXIX w.", "początek trzydziestego dziewiątego wieku"], 
  ["początku XXXIX w.", "początku trzydziestego dziewiątego wieku"], 
  ["w XXXVIII wieku", "w trzydziestym ósmym wieku"], 
  ["XXXVIII wieku", "trzydziestego ósmego wieku"], 
  ["XXXVIII wiek", "trzydziesty ósmy wiek"], 
  ["koniec XXXVIII w.", "koniec trzydziestego ósmego wieku"], 
  ["końca XXXVIII w.", "końca trzydziestego ósmego wieku"], 
  ["początek XXXVIII w.", "początek trzydziestego ósmego wieku"], 
  ["początku XXXVIII w.", "początku trzydziestego ósmego wieku"], 
  ["w XXXVII wieku", "w trzydziestym siódmym wieku"], 
  ["XXXVII wieku", "trzydziestego siódmego wieku"], 
  ["XXXVII wiek", "trzydziesty siódmy wiek"], 
  ["koniec XXXVII w.", "koniec trzydziestego siódmego wieku"], 
  ["końca XXXVII w.", "końca trzydziestego siódmego wieku"], 
  ["początek XXXVII w.", "początek trzydziestego siódmego wieku"], 
  ["początku XXXVII w.", "początku trzydziestego siódmego wieku"], 
  ["w XXXVI wieku", "w trzydziestym szóstym wieku"], 
  ["XXXVI wieku", "trzydziestego szóstego wieku"], 
  ["XXXVI wiek", "trzydziesty szósty wiek"], 
  ["koniec XXXVI w.", "koniec trzydziestego szóstego wieku"], 
  ["końca XXXVI w.", "końca trzydziestego szóstego wieku"], 
  ["początek XXXVI w.", "początek trzydziestego szóstego wieku"], 
  ["początku XXXVI w.", "początku trzydziestego szóstego wieku"], 
  ["w XXXV wieku", "w trzydziestym piątym wieku"], 
  ["XXXV wieku", "trzydziestego piątego wieku"], 
  ["XXXV wiek", "trzydziesty piąty wiek"], 
  ["koniec XXXV w.", "koniec trzydziestego piątego wieku"], 
  ["końca XXXV w.", "końca trzydziestego piątego wieku"], 
  ["początek XXXV w.", "początek trzydziestego piątego wieku"], 
  ["początku XXXV w.", "początku trzydziestego piątego wieku"], 
  ["w XXXIV wieku", "w trzydziestym czwartym wieku"], 
  ["XXXIV wieku", "trzydziestego czwartego wieku"], 
  ["XXXIV wiek", "trzydziesty czwarty wiek"], 
  ["koniec XXXIV w.", "koniec trzydziestego czwartego wieku"], 
  ["końca XXXIV w.", "końca trzydziestego czwartego wieku"], 
  ["początek XXXIV w.", "początek trzydziestego czwartego wieku"], 
  ["początku XXXIV w.", "początku trzydziestego czwartego wieku"], 
  ["w XXXIII wieku", "w trzydziestym trzecim wieku"], 
  ["XXXIII wieku", "trzydziestego trzeciego wieku"], 
  ["XXXIII wiek", "trzydziesty trzeci wiek"], 
  ["koniec XXXIII w.", "koniec trzydziestego trzeciego wieku"], 
  ["końca XXXIII w.", "końca trzydziestego trzeciego wieku"], 
  ["początek XXXIII w.", "początek trzydziestego trzeciego wieku"], 
  ["początku XXXIII w.", "początku trzydziestego trzeciego wieku"], 
  ["w XXXII wieku", "w trzydziestym drugim wieku"], 
  ["XXXII wieku", "trzydziestego drugiego wieku"], 
  ["XXXII wiek", "trzydziesty drugi wiek"], 
  ["koniec XXXII w.", "koniec trzydziestego drugiego wieku"], 
  ["końca XXXII w.", "końca trzydziestego drugiego wieku"], 
  ["początek XXXII w.", "początek trzydziestego drugiego wieku"], 
  ["początku XXXII w.", "początku trzydziestego drugiego wieku"], 
  ["w XXXI wieku", "w trzydziestym pierwszym wieku"], 
  ["XXXI wieku", "trzydziestego pierwszego wieku"], 
  ["XXXI wiek", "trzydziesty pierwszy wiek"], 
  ["koniec XXXI w.", "koniec trzydziestego pierwszego wieku"], 
  ["końca XXXI w.", "końca trzydziestego pierwszego wieku"], 
  ["początek XXXI w.", "początek trzydziestego pierwszego wieku"], 
  ["początku XXXI w.", "początku trzydziestego pierwszego wieku"], 
  ["w XXX wieku", "w trzydziestym wieku"], 
  ["XXX wieku", "trzydziestego wieku"], 
  ["XXX wiek", "trzydziesty wiek"], 
  ["koniec XXX w.", "koniec trzydziestego wieku"], 
  ["końca XXX w.", "końca trzydziestego wieku"], 
  ["początek XXX w.", "początek trzydziestego wieku"], 
  ["początku XXX w.", "początku trzydziestego wieku"], 
  ["w XXIX wieku", "w dwudziestym dziewiątym wieku"], 
  ["XXIX wieku", "dwudziestego dziewiątego wieku"], 
  ["XXIX wiek", "dwudziesty dziewiąty wiek"], 
  ["koniec XXIX w.", "koniec dwudziestego dziewiątego wieku"], 
  ["końca XXIX w.", "końca dwudziestego dziewiątego wieku"], 
  ["początek XXIX w.", "początek dwudziestego dziewiątego wieku"], 
  ["początku XXIX w.", "początku dwudziestego dziewiątego wieku"], 
  ["w XXVIII wieku", "w dwudziestym ósmym wieku"], 
  ["XXVIII wieku", "dwudziestego ósmego wieku"], 
  ["XXVIII wiek", "dwudziesty ósmy wiek"], 
  ["koniec XXVIII w.", "koniec dwudziestego ósmego wieku"], 
  ["końca XXVIII w.", "końca dwudziestego ósmego wieku"], 
  ["początek XXVIII w.", "początek dwudziestego ósmego wieku"], 
  ["początku XXVIII w.", "początku dwudziestego ósmego wieku"], 
  ["w XXVII wieku", "w dwudziestym siódmym wieku"], 
  ["XXVII wieku", "dwudziestego siódmego wieku"], 
  ["XXVII wiek", "dwudziesty siódmy wiek"], 
  ["koniec XXVII w.", "koniec dwudziestego siódmego wieku"], 
  ["końca XXVII w.", "końca dwudziestego siódmego wieku"], 
  ["początek XXVII w.", "początek dwudziestego siódmego wieku"], 
  ["początku XXVII w.", "początku dwudziestego siódmego wieku"], 
  ["w XXVI wieku", "w dwudziestym szóstym wieku"], 
  ["XXVI wieku", "dwudziestego szóstego wieku"], 
  ["XXVI wiek", "dwudziesty szósty wiek"], 
  ["koniec XXVI w.", "koniec dwudziestego szóstego wieku"], 
  ["końca XXVI w.", "końca dwudziestego szóstego wieku"], 
  ["początek XXVI w.", "początek dwudziestego szóstego wieku"], 
  ["początku XXVI w.", "początku dwudziestego szóstego wieku"], 
  ["w XXV wieku", "w dwudziestym piątym wieku"], 
  ["XXV wieku", "dwudziestego piątego wieku"], 
  ["XXV wiek", "dwudziesty piąty wiek"], 
  ["koniec XXV w.", "koniec dwudziestego piątego wieku"], 
  ["końca XXV w.", "końca dwudziestego piątego wieku"], 
  ["początek XXV w.", "początek dwudziestego piątego wieku"], 
  ["początku XXV w.", "początku dwudziestego piątego wieku"], 
  ["w XXIV wieku", "w dwudziestym czwartym wieku"], 
  ["XXIV wieku", "dwudziestego czwartego wieku"], 
  ["XXIV wiek", "dwudziesty czwarty wiek"], 
  ["koniec XXIV w.", "koniec dwudziestego czwartego wieku"], 
  ["końca XXIV w.", "końca dwudziestego czwartego wieku"], 
  ["początek XXIV w.", "początek dwudziestego czwartego wieku"], 
  ["początku XXIV w.", "początku dwudziestego czwartego wieku"], 
  ["w XXIII wieku", "w dwudziestym trzecim wieku"], 
  ["XXIII wieku", "dwudziestego trzeciego wieku"], 
  ["XXIII wiek", "dwudziesty trzeci wiek"], 
  ["koniec XXIII w.", "koniec dwudziestego trzeciego wieku"], 
  ["końca XXIII w.", "końca dwudziestego trzeciego wieku"], 
  ["początek XXIII w.", "początek dwudziestego trzeciego wieku"], 
  ["początku XXIII w.", "początku dwudziestego trzeciego wieku"], 
  ["w XXII wieku", "w dwudziestym drugim wieku"], 
  ["XXII wieku", "dwudziestego drugiego wieku"], 
  ["XXII wiek", "dwudziesty drugi wiek"], 
  ["koniec XXII w.", "koniec dwudziestego drugiego wieku"], 
  ["końca XXII w.", "końca dwudziestego drugiego wieku"], 
  ["początek XXII w.", "początek dwudziestego drugiego wieku"], 
  ["początku XXII w.", "początku dwudziestego drugiego wieku"], 
  ["w XXI wieku", "w dwudziestym pierwszym wieku"], 
  ["XXI wieku", "dwudziestego pierwszego wieku"], 
  ["XXI wiek", "dwudziesty pierwszy wiek"], 
  ["koniec XXI w.", "koniec dwudziestego pierwszego wieku"], 
  ["końca XXI w.", "końca dwudziestego pierwszego wieku"], 
  ["początek XXI w.", "początek dwudziestego pierwszego wieku"], 
  ["początku XXI w.", "początku dwudziestego pierwszego wieku"], 
  ["w XX wieku", "w dwudziestym wieku"], 
  ["XX wieku", "dwudziestego wieku"], 
  ["XX wiek", "dwudziesty wiek"], 
  ["koniec XX w.", "koniec dwudziestego wieku"], 
  ["końca XX w.", "końca dwudziestego wieku"], 
  ["początek XX w.", "początek dwudziestego wieku"], 
  ["początku XX w.", "początku dwudziestego wieku"], 
  ["w XIX wieku", "w dziewiętnastym wieku"], 
  ["XIX wieku", "dziewiętnastego wieku"], 
  ["XIX wiek", "dziewiętnasty wiek"], 
  ["koniec XIX w.", "koniec dziewiętnastego wieku"], 
  ["końca XIX w.", "końca dziewiętnastego wieku"], 
  ["początek XIX w.", "początek dziewiętnastego wieku"], 
  ["początku XIX w.", "początku dziewiętnastego wieku"], 
  ["w XVIII wieku", "w osiemnastym wieku"], 
  ["XVIII wieku", "osiemnastego wieku"], 
  ["XVIII wiek", "osiemnasty wiek"], 
  ["koniec XVIII w.", "koniec osiemnastego wieku"], 
  ["końca XVIII w.", "końca osiemnastego wieku"], 
  ["początek XVIII w.", "początek osiemnastego wieku"], 
  ["początku XVIII w.", "początku osiemnastego wieku"], 
  ["w XVII wieku", "w siedemnastym wieku"], 
  ["XVII wieku", "siedemnastego wieku"], 
  ["XVII wiek", "siedemnasty wiek"], 
  ["koniec XVII w.", "koniec siedemnastego wieku"], 
  ["końca XVII w.", "końca siedemnastego wieku"], 
  ["początek XVII w.", "początek siedemnastego wieku"], 
  ["początku XVII w.", "początku siedemnastego wieku"], 
  ["w XVI wieku", "w szesnastym wieku"], 
  ["XVI wieku", "szesnastego wieku"], 
  ["XVI wiek", "szesnasty wiek"], 
  ["koniec XVI w.", "koniec szesnastego wieku"], 
  ["końca XVI w.", "końca szesnastego wieku"], 
  ["początek XVI w.", "początek szesnastego wieku"], 
  ["początku XVI w.", "początku szesnastego wieku"], 
  ["w XV wieku", "w piętnastym wieku"], 
  ["XV wieku", "piętnastego wieku"], 
  ["XV wiek", "piętnasty wiek"], 
  ["koniec XV w.", "koniec piętnastego wieku"], 
  ["końca XV w.", "końca piętnastego wieku"], 
  ["początek XV w.", "początek piętnastego wieku"], 
  ["początku XV w.", "początku piętnastego wieku"], 
  ["w XIV wieku", "w czternastym wieku"], 
  ["XIV wieku", "czternastego wieku"], 
  ["XIV wiek", "czternasty wiek"], 
  ["koniec XIV w.", "koniec czternastego wieku"], 
  ["końca XIV w.", "końca czternastego wieku"], 
  ["początek XIV w.", "początek czternastego wieku"], 
  ["początku XIV w.", "początku czternastego wieku"], 
  ["w XIII wieku", "w trzynastym wieku"], 
  ["XIII wieku", "trzynastego wieku"], 
  ["XIII wiek", "trzynasty wiek"], 
  ["koniec XIII w.", "koniec trzynastego wieku"], 
  ["końca XIII w.", "końca trzynastego wieku"], 
  ["początek XIII w.", "początek trzynastego wieku"], 
  ["początku XIII w.", "początku trzynastego wieku"], 
  ["w XII wieku", "w dwunastym wieku"], 
  ["XII wieku", "dwunastego wieku"], 
  ["XII wiek", "dwunasty wiek"], 
  ["koniec XII w.", "koniec dwunastego wieku"], 
  ["końca XII w.", "końca dwunastego wieku"], 
  ["początek XII w.", "początek dwunastego wieku"], 
  ["początku XII w.", "początku dwunastego wieku"], 
  ["w XI wieku", "w jedenastym wieku"], 
  ["XI wieku", "jedenastego wieku"], 
  ["XI wiek", "jedenasty wiek"], 
  ["koniec XI w.", "koniec jedenastego wieku"], 
  ["końca XI w.", "końca jedenastego wieku"], 
  ["początek XI w.", "początek jedenastego wieku"], 
  ["początku XI w.", "początku jedenastego wieku"], 
  ["w X wieku", "w dziesiątym wieku"], 
  ["X wieku", "dziesiątego wieku"], 
  ["X wiek", "dziesiąty wiek"], 
  ["koniec X w.", "koniec dziesiątego wieku"], 
  ["końca X w.", "końca dziesiątego wieku"], 
  ["początek X w.", "początek dziesiątego wieku"], 
  ["początku X w.", "początku dziesiątego wieku"], 
  ["w IX wieku", "w dziewiątym wieku"], 
  ["IX wieku", "dziewiątego wieku"], 
  ["IX wiek", "dziewiąty wiek"], 
  ["koniec IX w.", "koniec dziewiątego wieku"], 
  ["końca IX w.", "końca dziewiątego wieku"], 
  ["początek IX w.", "początek dziewiątego wieku"], 
  ["początku IX w.", "początku dziewiątego wieku"], 
  ["w VIII wieku", "w ósmym wieku"], 
  ["VIII wieku", "ósmego wieku"], 
  ["VIII wiek", "ósmy wiek"], 
  ["koniec VIII w.", "koniec ósmego wieku"], 
  ["końca VIII w.", "końca ósmego wieku"], 
  ["początek VIII w.", "początek ósmego wieku"], 
  ["początku VIII w.", "początku ósmego wieku"], 
  ["w VII wieku", "w siódmym wieku"], 
  ["VII wieku", "siódmego wieku"], 
  ["VII wiek", "siódmy wiek"], 
  ["koniec VII w.", "koniec siódmego wieku"], 
  ["końca VII w.", "końca siódmego wieku"], 
  ["początek VII w.", "początek siódmego wieku"], 
  ["początku VII w.", "początku siódmego wieku"], 
  ["w VI wieku", "w szóstym wieku"], 
  ["VI wieku", "szóstego wieku"], 
  ["VI wiek", "szósty wiek"], 
  ["koniec VI w.", "koniec szóstego wieku"], 
  ["końca VI w.", "końca szóstego wieku"], 
  ["początek VI w.", "początek szóstego wieku"], 
  ["początku VI w.", "początku szóstego wieku"], 
  ["w V wieku", "w piątym wieku"], 
  ["V wieku", "piątego wieku"], 
  ["V wiek", "piąty wiek"], 
  ["koniec V w.", "koniec piątego wieku"], 
  ["końca V w.", "końca piątego wieku"], 
  ["początek V w.", "początek piątego wieku"], 
  ["początku V w.", "początku piątego wieku"], 
  ["w IV wieku", "w czwartym wieku"], 
  ["IV wieku", "czwartego wieku"], 
  ["IV wiek", "czwarty wiek"], 
  ["koniec IV w.", "koniec czwartego wieku"], 
  ["końca IV w.", "końca czwartego wieku"], 
  ["początek IV w.", "początek czwartego wieku"], 
  ["początku IV w.", "początku czwartego wieku"], 
  ["w III wieku", "w trzecim wieku"], 
  ["III wieku", "trzeciego wieku"], 
  ["III wiek", "trzeci wiek"], 
  ["koniec III w.", "koniec trzeciego wieku"], 
  ["końca III w.", "końca trzeciego wieku"], 
  ["początek III w.", "początek trzeciego wieku"], 
  ["początku III w.", "początku trzeciego wieku"], 
  ["w II wieku", "w drugim wieku"], 
  ["II wieku", "drugiego wieku"], 
  ["II wiek", "drugi wiek"], 
  ["koniec II w.", "koniec drugiego wieku"], 
  ["końca II w.", "końca drugiego wieku"], 
  ["początek II w.", "początek drugiego wieku"], 
  ["początku II w.", "początku drugiego wieku"], 
  ["w I wieku", "w pierwszym wieku"], 
  ["I wieku", "pierwszego wieku"], 
  ["I wiek", "pierwszy wiek"], 
  ["koniec I w.", "koniec pierwszego wieku"], 
  ["końca I w.", "końca pierwszego wieku"], 
  ["początek I w.", "początek pierwszego wieku"], 
  ["początku I w.", "początku pierwszego wieku"]
]